# 문서 요약 (Text Summarization)

In [3]:
# 패키지 업그레이드로 인한 에러 처리를 위해 라이브러리 버전 Downgrade
!pip install 'networkx<2.7'

# 런타임 재시작할 것

������ ������ ã�� �� �����ϴ�.


# 0 데이터 준비

In [1]:
doc = """업종을 가리지 않고 다양한 국내 기업들이 우주산업을 ‘미래 먹거리’로 주목하고 있다. 여러 우주산업 분야 중에서도 특히 비교적 진출 문턱이 낮은 ‘스페이스 데이터(Space Data)’에서 기회를 잡겠단 청사진을 그렸다.

26일 업계에 따르면 정보통신기술(ICT) 업체부터 방산 기업까지 정부의 우주산업 육성 계획에 맞춰 스페이스 데이터 시장 진출을 준비하고 있다. ‘우주 데이터 산업의 쌀’로 비유되는 스페이스 데이터는 인공위성에서 촬영한 지구 관측 영상·이미지 등 우주를 통해 오가는 다양한 정보들을 통틀어 부르는 말이다. 인공지능(AI)·빅데이터 등을 활용해 △국토·자원 관리 △재해·재난 대응 △농업 △금융 △부동산 △물류 △환경 등 매우 다양한 산업에서 새로운 사업적 가치가 창출될 것으로 기대받는 분야다.

정부는 과학기술정보통신부(과기정통부)를 중심으로 스페이스 데이터 시장의 기반이 되는 인공위성 분야는 물론 우주 발사체 등을 개발하는 사업을 추진하고 있다. 이를 통해 민간 주도의 우주산업 생태계를 육성하겠단 목표를 세웠다.

전통적인 ICT 기업인 이동통신 3사(SK텔레콤·KT·LG유플러스, 이하 이통3사)는 이 같은 분위기를 반영, 인공위성을 기반으로 한 데이터 시장을 차세대 사업으로 선정했다. 네이버·한글과컴퓨터(한컴) 등 플랫폼 기업도 마찬가지다. 이들 기업은 그간 쌓아온 자사 인프라에 ‘스페이스 데이터’를 추가하는 식으로 사업을 구상 중이다.

최근에는 방산 기업인 LIG넥스원과 한국항공우주산업(KAI) 등도 해당 시장에서 사업적 성과를 올리기 위해 협업의 폭을 확대하고 있다. 스페이스 데이터뿐 아니라 인공위성 제작에도 관심을 나타내며 사업 영역을 넓히기 위한 전략을 추진 중이다.

국내 굴지의 기업들이 스페이스 데이터 시장에 주목하는 이유는 국내 우주산업 생태계의 모습이 반영된 현상으로 보인다. 정부 발표에 따르면 2020년 기준 우리나라 우주산업 규모는 3조2610억원 수준이다. 세계 우주산업 시장 규모는 2019년 기준 2707억달러(약 300조원)이고, 각 정부의 우주개발 예산을 포함하면 3660억달러(약 450조원)까지 증가한다. 우리나라 우주산업은 이 중 약 1%를 차지하고 있을 정도로 영세하다.

이마저도 위성방송통신·항법 분야가 2조5378억원을 기록, 전체의 78%를 차지하고 있을 정도로 치우쳐있다. 위성제조는 3249억원(10%), 발사체 제작은 1913억원(6%)으로 그 규모가 무척 작다.

우주 산업계 관계자는 “국내 다양한 기업들이 스페이스 데이터 사업에서 새로운 기회를 발굴하고자 하는 이유는 해당 분야의 성장 가능성을 반영한 것”이라면서도 “국내 우주산업 생태계를 고려하면 사업적 성과를 올릴 수 있다고 판단되는 분야가 사실상 스페이스 데이터 뿐이기도 하다”고 말했다.

누리호 2차 발사의 성공으로 우리나라는 세계에서 7번째로 1.5t급 실용위성을 자체적으로 지구궤도에 올릴 수 있는 국가가 됐다. 그러나 발사체·위성 등 우주기기를 제작할 수 있는 민간의 능력은 현저하게 떨어진다. 업계 관계자는 “우리나라 기업 중 발사체·위성 제작 분야에 진출해 세계 시장에서 유의미한 성과를 낼 수 있는 곳은 없다”며 “스페이스 데이터 외 다른 분야에 진출하고 싶어도 기업 입장에선 리스크(위험성)가 커 선뜻 나서기 힘들다”고 강조했다. 성장성이 담보됐다고 평가되는 우주산업이지만 현재 국내 수준으론 진출 분야가 한정적이란 설명이다.

국내 기업이 거의 유일하게 진출할 수 있는 스페이스 데이터 시장이지만, 기회는 충분하단 평가가 나온다. 또 다른 우주 산업계 관계자는 국내 기업이 스페이스 데이터 사업에서 올릴 수 있는 성과가 많다고 설명했다. 그는 “인공위성을 통해 확보한 데이터를 사용하는 곳은 결국 지상”이라며 “IT강국을 이끄는 국내 기업들이 보유한 인공지능(AI)·통신·보안 등의 기술을 통해 데이터를 재가공하면 세계 시장에서 충분히 성과를 낼 수 있을 것”이라고 말했다.

정부의 지원 역시 기대되는 요소로 꼽힌다. 정부는 2022년부터 2031년까지 공공목적의 위성을 총 170여기 개발하고, 위성개발과 연계해 국내 발사체 발사도 총 40여회 추진한다. 이 과정을 국내 기업과 함께 진행, 민간이 자연스럽게 기술을 습득하도록 사업을 기획했다.

누리호의 성공 역시 스페이스 데이터 분야의 성장을 촉진할 요소다. 정부는 누리호의 기술을 민간에 이전해 우주산업 생태계를 키우겠단 계획을 진행하고 있다. 오는 9월엔 누리호의 기술을 이전받는 ‘체계종합기업 우선협상대상자’가 선정된다. 우리나라에서도 기업 간 협업을 통해 민간위성 발사가 가능해진단 의미다. 정부는 이와 관련 고흥 나로우주센터 내 ‘민간기업 전용 발사체 발사장’을 건설할 방침이다. 민간이 우주 운송 수단을 확보하게 된다면 자연스럽게 국내 스페이스 데이터 시장의 규모도 커질 수 있는 구조다.

미국 투자은행 모건스탠리는 글로벌 우주산업 규모가 2018년 3500억달러(약 420조원)에서 오는 2040년 1조1000억달러(약 1320조원)까지 연평균 5.3% 성장하리라 전망했다. 이에 따라 스페이스 데이터 시장의 성장도 가파를 것으로 분석된다. 마켓츠앤마켓츠는 위성 이미지 데이터 시장 규모가 2021년 59억달러(약 7조원)에서 2026년에는 그 규모가 3배 이상 성장, 167억달러(약 21조원)에 이를 것으로 봤다.

시장 변화에 민감한 이통3사는 ‘우주산업의 성장’에 맞춰 다양한 전략을 추진하고 있다. 민간 주도의 우주개발 시대를 의미하는 ‘뉴 스페이스(New Space)’에 대응하겠단 취지다. 이통3사 중에선 KT가 가장 적극적이다.

KT는 52년간 인공위성 사업을 영위해 온 KT SAT(샛)을 전면으로 내세워 사업을 준비하고 있다. KT 샛은 이 기간 쌓은 ‘국제 협력’을 바탕으로 스페이스 데이터 사업 진출을 준비 중이다. 지난 2월 미국 소재 위성영상 제공 및 분석기업인 ‘블랙스카이’와 협력을 시작, 고해상도의 위성 이미지를 공급받을 수 있는 기반을 마련했다. 지난 4월에는 AI기술 기반 공간정보분석기업인 ‘오비탈인사이트’와도 손을 잡았다. 이를 통해 공간정보분석 서비스를 우리나라 시장에 최초로 제공할 수 있게 됐다.

KT 샛은 구체적으로 △위성 이미지 수집 △데이터 전처리 △우주 데이터 분석·활용 등을 새로운 사업 범위로 삼았다. 데이터 전처리는 자료 원본(raw data)을 목적과 방법에 맞는 형태로 처리하기 위해 불필요한 정보를 제거하는 식의 가공 과정을 말한다.

KT 샛은 우선 국내 시장을 대상으로 레퍼런스를 확보, 스페이스 데이터 사업의 서비스 포트폴리오를 다각화를 추진한다. 향후 미래 성장 가능성이 높은 데이터 분석·활용 등의 부가가치 분야에 집중함으로써 세계 전역으로 사업 영역을 확대하겠다는 계획이다.

SKT는 과기정통부가 올 3분기 추진할 것으로 전망되는 ‘저궤도 군집 위성통신 시스템 개발사업’에 참여를 준비 중인 것으로 전해진다. 또 자회사인 SK텔링크를 통해 해외 위성통신 사업자와의 협력을 추진 중이다. 위성을 기반으로 한 6G 통신 서비스 공급을 준비하기 위한 목적으로 보인다.

LG유플러스 역시 인공위성과 관련된 기술을 확보하기 위해 한국과학기술원(KAIST·카이스트)과 공동 연구를 수행한 바 있다. 지난해 12월부터 이준구 카이스트 교수 연구팀 등과 6개월간 세계 최초로 상용화된 D-웨이브(D-wave) 양자컴퓨터를 사용, 6G 저궤도위성 네트워크망 구조 최적화 연구를 진행했다. 양측은 이번 연구를 통해 양자컴퓨터로 하나의 위성에서 통신할 수 있는 주변 위성의 개수와 거리를 정하고, 양자컴퓨터로 빠르게 계산하는 데 성공했다. 글로벌 통신장비 제조업체 노키아와는 5G 어드밴스드(Advanced·5G의 진화 단계) 및 6G 분야 연구개발을 협력하는 중이다.

한컴그룹에선 2020년 합류한 우주·드론 전문기업 한컴인스페이스가 스페이스 데이터 사업을 담당하고 있다.

한컴인스페이스는 지난 5월 국내 첫 지구관측용 민간위성 ‘세종1호’를 발사했다. 현재 정상 운용에 들어선 세종1호는 5m 해상도의 다중밴드 위성으로 농업, 산림 등 다양한 분야에서 위성영상 및 분석정보를 제공할 수 있다.

한컴인스페이스는 세종1호를 통해 획득한 데이터를 아시아 및 중동 지역 기업들을 대상으로 판매할 전략을 추진하고 있다. 해당 국가들은 농업 지역이 넓고 분쟁이 잦아 스페이스 데이터 수요가 높다. 한컴 측은 “이번 세종1호 발사를 통해 인공위성과 드론은 물론 완성형 초고해상도 센서를 기반으로 세계에서 유일하게 우주·항공·지상을 모두 커버하는 영상 데이터 서비스 벨트를 구축하게 된다”고 전했다.

한컴은 2023년 상반기에 세종2호를 추가로 발사할 계획이다. 하반기엔 3호와 4호의 발사를, 2024년엔 5호 발사를 준비 중이다. 5년 내 50기 이상을 발사, 군집위성 체계를 구축한다는 목표를 갖고 있다.

네이버는 클라우드 기반 위성 서비스 확대에 나선다. 네이버클라우드를 중심으로 최근 우주 위성체계 개발 기업 쎄트렉아이 등 국내 기업과 협력 체계를 구축하고 있다. 위성 정보를 안정적으로 처리하는 데 ‘클라우드 기술’을 활용하는 게 사업 기획의 핵심이다.

LIG넥스원은 최근 영국 판보로 에어쇼에서 아이스아이(ICEYE)와 ‘위성산업분야 업무협약(MOU)’을 체결했다. 양사는 이번 협약을 통해 △초소형 위성분야 △영상 활용·서비스분야 △뉴 스페이스 분야 기술·동향 교류 등의 협력을 추진한다. LIG넥스원은 주로 인공위성 탑재체로 활용되는 초정밀영상레이더(SAR) 기술을 보유한 기업이다. 회사는 악천후·구름 등에도 활용 가능한 SAR의 영상처리 기술을 기반으로 스페이스 데이터 분야뿐 아니라 위성 제조 분야에서도 성과를 낼 계획이다.

KAI는 카이스트와 손잡았다. 카이스트와의 협력을 통해 위성이 전송하는 사진을 저해상도에서 고해상도로 변환하는 초해상화 기술 등을 확보할 방침이다. 회사 측은 “우주산업 고도화에 필요한 핵심기술 공동 연구개발로 세계 시장에 본격 진출한다”고 전했다. 지난 4월 항공 영상분석 전문업체인 메이사메이사와법인(JV) 메이사메이사플래닛(Meissaanet)을 설립하기도 했다.

업계 관계자는 “정부의 육성 정책에 맞춰 국내 굴지의 기업들이 각자의 장점을 살려 우주산업 시장에 진출하기 위한 움직임이 활발하다”며 “다만 이 같은 사업들이 시장에 안착하려면 10년 정도의 시간이 필요할 것”이라고 말했다."""

## Mecab 설치 (필요시)

In [11]:
!sudo apt-get install g++ openjdk-8-jdk 
# !sudo apt-get install python-dev; pip install konlpy     # Python 2.x
!sudo apt-get install python3-dev; pip3 install konlpy   # Python 3.x
!sudo apt-get install curl
!bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)

'sudo'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
'sudo'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
'sudo'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.


������ ������ ã�� �� �����ϴ�.


# 1 Luhn Summarizer

http://courses.ischool.berkeley.edu/i256/f06/papers/luhn58.pdf

Hans Peter Luhn

https://en.wikipedia.org/wiki/Hans_Peter_Luhn

 Hans Peter Luhn은 공학과 정보과학에서의 개척 작업으로 "정보 검색의 아버지"로 알려져 있다. 그는 표제어가 문맥에 포함된 채 배열된 색인(KWIC : keyword-in-context) 개발, 정보 선택 제공(SDI), 완전 텍스트 프로세싱, 자동 발췌(요약), 단어 시소로스의 최초 현대식 사용으로 신뢰를 얻었다. 오늘날 파생된 지식 대부분에는 KWIC 색인이 있으며 과학의 모든 분야에 SDI시스템이 있다. 


 Luhn은 1896년 7월 1일 독일 바르멘에서 태어났다. 아버지가 그 당시 유명한 인쇄업자였으므로, 스위스에서 인쇄업을 배웠다. 어렸을 때무터 그는 창조성이 뛰어난 재능을 보였으며, 기술적 문제, 물리학, 통계학에 관심을 보였다. 그러나 1차 세계대전으로 독일군 통신장교로 복역(1915년1917년)하면서 프랑스 터키 루마니아 불가리아 등지로 옮겨 다녀야만 했다. 1차 대전 이후 그는 스위스의 Gallen 교회 Schweizwrische handels Hochschule로 돌아와 기술, 물리학, 회계분야의 수업을 들었다. 그 후, Luhn은 그리스에서 못다한 공부에 전념했으며, 더블부기기계(Duble-Entry Bookeeping Machine : 카드 대장에 대변기입과 차변 기입을 기록할 수 있는 것)를 발명하였다. 그는 또 Hollerith tabulating/recording machine에 정통했고, 천공카드에서 문자 숫자를 나타내는 장치의 사용을 증가시키게 했다. 1920년부터 1930년까지는 10개의 특허권을 획득하여 그의 탁월한 능력을 보여주었다. 그것들중에 루노메터(Lunometer : 직물의 실길이를 계산하는데 쓰이는 장치)는 지금도 사용되고 있다.


 1920년까지 그는 직물 공장에서 일하기 시작했다. 그는 직물 공장의 사업확장을 위해 뉴잉글랜드에서 1924년 미국으로 가게 되었다. 그러나 회사가 곧 파산하였고 Luhn은 직장없이 뉴욕에 남게 되었다. 그는 은행에서 일을 하였고 곧 뉴욕 월스트리트에 소재한 국제어음은행(International Acceptance Bank)에서 재정담당관으로 승진하였다. 


 1933년 Luhn은 자사인 공학회사 H.P. Luhn & Association을 설립하였고 8년간 자문기술자로 일했다. 1941년 Luhn은 IBM에서 수석 연구기술자로 참여하였고 이후에 정보검색연구 관리자로 일했다. Luhn이 IBM에서 새로운 아이디어를 지속적으로 내놓고 문제를 다르게 접근하여 주목을 받는 동안, 다른 기술자들에게 고차원적인 창조를 하도록 자극하면서 그들의 촉매제 역할을 하여 신뢰를 얻었다

In [2]:
doc

'업종을 가리지 않고 다양한 국내 기업들이 우주산업을 ‘미래 먹거리’로 주목하고 있다. 여러 우주산업 분야 중에서도 특히 비교적 진출 문턱이 낮은 ‘스페이스 데이터(Space Data)’에서 기회를 잡겠단 청사진을 그렸다.\n\n26일 업계에 따르면 정보통신기술(ICT) 업체부터 방산 기업까지 정부의 우주산업 육성 계획에 맞춰 스페이스 데이터 시장 진출을 준비하고 있다. ‘우주 데이터 산업의 쌀’로 비유되는 스페이스 데이터는 인공위성에서 촬영한 지구 관측 영상·이미지 등 우주를 통해 오가는 다양한 정보들을 통틀어 부르는 말이다. 인공지능(AI)·빅데이터 등을 활용해 △국토·자원 관리 △재해·재난 대응 △농업 △금융 △부동산 △물류 △환경 등 매우 다양한 산업에서 새로운 사업적 가치가 창출될 것으로 기대받는 분야다.\n\n정부는 과학기술정보통신부(과기정통부)를 중심으로 스페이스 데이터 시장의 기반이 되는 인공위성 분야는 물론 우주 발사체 등을 개발하는 사업을 추진하고 있다. 이를 통해 민간 주도의 우주산업 생태계를 육성하겠단 목표를 세웠다.\n\n전통적인 ICT 기업인 이동통신 3사(SK텔레콤·KT·LG유플러스, 이하 이통3사)는 이 같은 분위기를 반영, 인공위성을 기반으로 한 데이터 시장을 차세대 사업으로 선정했다. 네이버·한글과컴퓨터(한컴) 등 플랫폼 기업도 마찬가지다. 이들 기업은 그간 쌓아온 자사 인프라에 ‘스페이스 데이터’를 추가하는 식으로 사업을 구상 중이다.\n\n최근에는 방산 기업인 LIG넥스원과 한국항공우주산업(KAI) 등도 해당 시장에서 사업적 성과를 올리기 위해 협업의 폭을 확대하고 있다. 스페이스 데이터뿐 아니라 인공위성 제작에도 관심을 나타내며 사업 영역을 넓히기 위한 전략을 추진 중이다.\n\n국내 굴지의 기업들이 스페이스 데이터 시장에 주목하는 이유는 국내 우주산업 생태계의 모습이 반영된 현상으로 보인다. 정부 발표에 따르면 2020년 기준 우리나라 우주산업 규모는 3조2610억원 수준이다. 세계 우주산업 시장 규모는 2019년 기준 

In [ ]:
%pip install mecab-python3

In [ ]:
%pip install nltk

In [5]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

### 1) 토큰화

In [7]:
from konlpy.tag import Mecab
mecab = Mecab()
mecab.pos(doc)

[('업종', 'NNG'),
 ('을', 'JKO'),
 ('가리', 'VV'),
 ('지', 'EC'),
 ('않', 'VX'),
 ('고', 'EC'),
 ('다양', 'XR'),
 ('한', 'XSA+ETM'),
 ('국내', 'NNG'),
 ('기업', 'NNG'),
 ('들', 'XSN'),
 ('이', 'JKS'),
 ('우주', 'NNG'),
 ('산업', 'NNG'),
 ('을', 'JKO'),
 ('‘', 'SY'),
 ('미래', 'NNG'),
 ('먹거리', 'NNG'),
 ('’', 'SY'),
 ('로', 'JKB'),
 ('주목', 'NNG'),
 ('하', 'XSV'),
 ('고', 'EC'),
 ('있', 'VX'),
 ('다', 'EF'),
 ('.', 'SF'),
 ('여러', 'MM'),
 ('우주', 'NNG'),
 ('산업', 'NNG'),
 ('분야', 'NNG'),
 ('중', 'NNB'),
 ('에서', 'JKB'),
 ('도', 'JX'),
 ('특히', 'MAG'),
 ('비교', 'NNG'),
 ('적', 'XSN'),
 ('진출', 'NNG'),
 ('문턱', 'NNG'),
 ('이', 'JKS'),
 ('낮', 'VA'),
 ('은', 'ETM'),
 ('‘', 'SY'),
 ('스페이스', 'NNP'),
 ('데이터', 'NNG'),
 ('(', 'SSO'),
 ('Space', 'SL'),
 ('Data', 'SL'),
 (')', 'SSC'),
 ('’', 'SY'),
 ('에서', 'JKB'),
 ('기회', 'NNG'),
 ('를', 'JKO'),
 ('잡', 'VV'),
 ('겠', 'EP'),
 ('단', 'ETM'),
 ('청사진', 'NNG'),
 ('을', 'JKO'),
 ('그렸', 'VV+EP'),
 ('다', 'EF'),
 ('.', 'SF'),
 ('26', 'SN'),
 ('일', 'NNBC'),
 ('업계', 'NNG'),
 ('에', 'JKB'),
 ('따르', 'VV'),
 (

In [36]:
from nltk.tokenize import sent_tokenize
from konlpy.tag import Mecab

# 문장 분리
def get_sentences(txt) : #(txt:str) -> list[str]:
    return sent_tokenize(txt)

# 토큰화 
def get_words(txt): #(txt:str) -> list[str]:
    mecab = Mecab()
    return [t[0] for t in mecab.pos(txt) if (t[1][0] == 'N') & (len(t[0])>1)]

In [35]:
# get_words = []
# for t in mecab.pos(doc):
#     if (t[1][0] == "N") and len(t[0])>1:
#         get_words.append(t[0])

# get_words

['업종',
 '국내',
 '기업',
 '우주',
 '산업',
 '미래',
 '먹거리',
 '주목',
 '우주',
 '산업',
 '분야',
 '비교',
 '진출',
 '문턱',
 '스페이스',
 '데이터',
 '기회',
 '청사진',
 '업계',
 '정보',
 '통신',
 '기술',
 '업체',
 '방산',
 '기업',
 '정부',
 '우주',
 '산업',
 '육성',
 '계획',
 '스페이스',
 '데이터',
 '시장',
 '진출',
 '준비',
 '우주',
 '데이터',
 '산업',
 '비유',
 '스페이스',
 '데이터',
 '인공위성',
 '촬영',
 '지구',
 '관측',
 '영상',
 '이미지',
 '우주',
 '정보',
 '인공지능',
 '데이터',
 '활용',
 '국토',
 '자원',
 '관리',
 '재해',
 '재난',
 '대응',
 '농업',
 '금융',
 '부동산',
 '물류',
 '환경',
 '산업',
 '사업',
 '가치',
 '창출',
 '기대',
 '분야',
 '정부',
 '과학',
 '기술',
 '정보',
 '통신부',
 '과기',
 '정통부',
 '중심',
 '스페이스',
 '데이터',
 '시장',
 '기반',
 '인공위성',
 '분야',
 '우주',
 '발사체',
 '개발',
 '사업',
 '추진',
 '민간',
 '주도',
 '우주',
 '산업',
 '생태계',
 '육성',
 '목표',
 '전통',
 '기업인',
 '동통',
 '텔레콤',
 '플러스',
 '이하',
 '이통',
 '분위기',
 '반영',
 '인공위성',
 '기반',
 '데이터',
 '시장',
 '차세대',
 '사업',
 '선정',
 '네이버',
 '한글',
 '컴퓨터',
 '한컴',
 '플랫',
 '기업',
 '마찬가지',
 '기업',
 '그간',
 '자사',
 '인프라',
 '스페이스',
 '데이터',
 '추가',
 '사업',
 '구상',
 '최근',
 '방산',
 '기업',
 '넥스',
 '한국',
 '항공우주',
 '산업',
 '해당',
 '시장',
 '

In [10]:
sent_tokenize?

Signature: sent_tokenize(text, language='english')
Docstring:
Return a sentence-tokenized copy of *text*,
using NLTK's recommended sentence tokenizer
(currently :class:`.PunktSentenceTokenizer`
for the specified language).

:param text: text to split into sentences
:param language: the model name in the Punkt corpus
File:      c:\users\user\anaconda3\envs\mecab\lib\site-packages\nltk\tokenize\__init__.py
Type:      function

In [11]:
get_sentences(doc)

['업종을 가리지 않고 다양한 국내 기업들이 우주산업을 ‘미래 먹거리’로 주목하고 있다.',
 '여러 우주산업 분야 중에서도 특히 비교적 진출 문턱이 낮은 ‘스페이스 데이터(Space Data)’에서 기회를 잡겠단 청사진을 그렸다.',
 '26일 업계에 따르면 정보통신기술(ICT) 업체부터 방산 기업까지 정부의 우주산업 육성 계획에 맞춰 스페이스 데이터 시장 진출을 준비하고 있다.',
 '‘우주 데이터 산업의 쌀’로 비유되는 스페이스 데이터는 인공위성에서 촬영한 지구 관측 영상·이미지 등 우주를 통해 오가는 다양한 정보들을 통틀어 부르는 말이다.',
 '인공지능(AI)·빅데이터 등을 활용해 △국토·자원 관리 △재해·재난 대응 △농업 △금융 △부동산 △물류 △환경 등 매우 다양한 산업에서 새로운 사업적 가치가 창출될 것으로 기대받는 분야다.',
 '정부는 과학기술정보통신부(과기정통부)를 중심으로 스페이스 데이터 시장의 기반이 되는 인공위성 분야는 물론 우주 발사체 등을 개발하는 사업을 추진하고 있다.',
 '이를 통해 민간 주도의 우주산업 생태계를 육성하겠단 목표를 세웠다.',
 '전통적인 ICT 기업인 이동통신 3사(SK텔레콤·KT·LG유플러스, 이하 이통3사)는 이 같은 분위기를 반영, 인공위성을 기반으로 한 데이터 시장을 차세대 사업으로 선정했다.',
 '네이버·한글과컴퓨터(한컴) 등 플랫폼 기업도 마찬가지다.',
 '이들 기업은 그간 쌓아온 자사 인프라에 ‘스페이스 데이터’를 추가하는 식으로 사업을 구상 중이다.',
 '최근에는 방산 기업인 LIG넥스원과 한국항공우주산업(KAI) 등도 해당 시장에서 사업적 성과를 올리기 위해 협업의 폭을 확대하고 있다.',
 '스페이스 데이터뿐 아니라 인공위성 제작에도 관심을 나타내며 사업 영역을 넓히기 위한 전략을 추진 중이다.',
 '국내 굴지의 기업들이 스페이스 데이터 시장에 주목하는 이유는 국내 우주산업 생태계의 모습이 반영된 현상으로 보인다.',
 '정부 발표에 따르면 2020년 기준 우리나라 우주산업 규모는 3

### 2) 중요 단어 결정

In [13]:
word_list = ['바나나','사과','바나나','바나나','포도']

In [14]:
# 단어별 빈도 수 카운팅 - Counter 대신 코드로 표현
counter = {}
for word in word_list:
    if word in counter:
        counter[word] += 1
    else:
        counter[word] = 1
    # 1. dict get method 활용
    # 2. 조건표현식 활용 
counter

{'바나나': 3, '사과': 1, '포도': 1}

In [15]:
from collections import Counter
counter = Counter(word_list)
counter

Counter({'바나나': 3, '사과': 1, '포도': 1})

In [16]:
# 단어 빈도 비율
total_tokens = sum(counter.values())
for key, value in counter.items():
    print(key, value, value/total_tokens)

바나나 3 0.6
사과 1 0.2
포도 1 0.2


In [17]:
from collections import Counter
# 단어(토큰)의 가중치 계산 및 범위에 포함되는 토큰 식별 
def get_keywords(word_list , min_ratio=0.001, max_ratio=0.5) :
    assert (min_ratio < 1 and max_ratio < 1)
    
    # 토큰별로 빈도수 카운팅
    counter = Counter(word_list)
    
    # 분석 문서의 총 토큰수 대비 해당 토큰의 빈도 비율 (해당 비율이 범위 이내 : keywords에 추가)
    keywords = set()
    
    total_tokens = sum(counter.values())
    for key, value in counter.items():
        if min_ratio <= value/total_tokens <= max_ratio:
            keywords.add(key)
    
    return keywords

get_keywords(['바나나','사과','바나나','바나나','포도'])

{'사과', '포도'}

### 3) 문장 중요도 계산

In [18]:
print('테스트' in {'토큰', 'abc'})
print('abc' in {'토큰', 'abc'})

False
True


In [25]:
# 문장의 가중치 계산
def get_sentence_weight(sentence: str, keywords):
    tokens = sentence.split(' ')
    window_start = 0; window_end = -1
    
    # 문장내에서 윈도 시작 위치 탐색 (중요단어인 경우 체크)
    for idx, token in enumerate(tokens):
        if token in keywords:
            window_start = idx
            break
    
    # 문장내에서 윈도 종료 위치 탐색
    for idx, token in enumerate(tokens):
        if token in keywords:
            window_end = idx+1
    
    # 윈도의 시작위치가 종료위치보다 큰경우 => 분석할 단어(토큰)가 없는 경우 종료
    if window_start > window_end:
        return 0
    
    # 윈도 크기 계산
    window_size = window_end - window_start
    
    # 분석 대상 문장 중 범위(0.001 ~ 0.5)에 포함된 토큰 개수 카운팅
    cnt = 0
    for idx in range(window_start, window_end):
        if tokens[idx] in keywords:
            cnt += 1
    
    # (분석 대상 문장 중 범위(0.001 ~ 0.5)에 포함된 토큰 개수)**2 / 윈도사이즈
    return cnt**2 / window_size

### 4) 문서 요약

In [37]:
# 문서 요약

# 함수들을 유기적으로 연결
def summarize(content, max_no_of_sentences = 10): # -> list:
    # get_sentences(txt) # input: 문서 (str) / output: 문장들 (str)
    # get_words(txt) # input: 문장, 문서 (str) / output: 길이가 1보다 큰 명사 토큰들 (str)
    # get_keywords(word_list) # input: 토큰 리스트 / output: 키워드들 (set)
    # get_sentence_weight(sentence, keywords) # input: sentence: 문장(str), / output: float

    doc_tokens = get_words(content)
    keywords = get_keywords(doc_tokens)

    sents = get_sentences(content)
    result = []
    for sent in sents:
        org_sent = sent
        sent = ' '.join(get_words(sent))
        sent_score = get_sentence_weight(sent, keywords) # sent를 어떻게 넣어줘야 하는지

        result.append((org_sent, sent_score))

    result = sorted(result, key=lambda x: -x[1])
    return result[:max_no_of_sentences] # 중요문장 10개 반환

In [38]:
li = summarize(doc, 3)
for s in li :
    print(s)

('우주 산업계 관계자는 “국내 다양한 기업들이 스페이스 데이터 사업에서 새로운 기회를 발굴하고자 하는 이유는 해당 분야의 성장 가능성을 반영한 것”이라면서도 “국내 우주산업 생태계를 고려하면 사업적 성과를 올릴 수 있다고 판단되는 분야가 사실상 스페이스 데이터 뿐이기도 하다”고 말했다.', 29.0)
('업계 관계자는 “정부의 육성 정책에 맞춰 국내 굴지의 기업들이 각자의 장점을 살려 우주산업 시장에 진출하기 위한 움직임이 활발하다”며 “다만 이 같은 사업들이 시장에 안착하려면 10년 정도의 시간이 필요할 것”이라고 말했다.', 22.0)
('업계 관계자는 “우리나라 기업 중 발사체·위성 제작 분야에 진출해 세계 시장에서 유의미한 성과를 낼 수 있는 곳은 없다”며 “스페이스 데이터 외 다른 분야에 진출하고 싶어도 기업 입장에선 리스크(위험성)가 커 선뜻 나서기 힘들다”고 강조했다.', 21.0)




---



# 2 Textrank

![대체 텍스트](https://www.researchgate.net/profile/Khushboo_Thakkar3/publication/232645575/figure/fig1/AS:575720050573312@1514273764062/Sample-graph-build-for-sentence-extraction.png)

## 2.1 TextRank 직접 구현하기 (Matrix 활용)

### 1) 자카드 유사도

In [70]:
Text = "딸기 바나나 사과 파인애플 수박. 바나나 사과 딸기 포도. 복숭아 수박. 파인애플 사과 딸기 바나나."

In [71]:
sentences = list(filter(None, Text.split('.')))
sentences = [sent.strip() for sent in sentences]
sentences

['딸기 바나나 사과 파인애플 수박', '바나나 사과 딸기 포도', '복숭아 수박', '파인애플 사과 딸기 바나나']

In [72]:
# 문장간 유사도 측정 (자카드 유사도 사용)
def sentence_similarity(sentence1:str, sentence2:str) -> float:
    tokens1 = sentence1.split()
    tokens2 = sentence2.split()
    set_token1 = set(tokens1)
    set_token2 = set(tokens2)
    
    print(set_token1)
    print(set_token2)
    print(set_token1.intersection(set_token2))
    print(set_token1.union(set_token2))

    return len(set_token1.intersection(set_token2)) / len(set_token1.union(set_token2))
     

sentence_similarity('나는 치킨을 좋아해','나는 치킨을 싫어해')

{'나는', '치킨을', '좋아해'}
{'나는', '치킨을', '싫어해'}
{'나는', '치킨을'}
{'나는', '치킨을', '좋아해', '싫어해'}


0.5

### 2) 그래프 생성

In [73]:
sentences

['딸기 바나나 사과 파인애플 수박', '바나나 사과 딸기 포도', '복숭아 수박', '파인애플 사과 딸기 바나나']

In [74]:
import numpy as np

# nodes(scores)
nodes = sentences
node_scores = [1.0] * len(sentences)

# edges
edges = []
# (시작 문장, 끝 문장, 유사도)

for start_idx in range(len(sentences) -1):
    for end_idx in range(start_idx +1, len(sentences)):
        sim = sentence_similarity(nodes[start_idx], nodes[end_idx])
        if sim:  # 유사도 0 제외
            edges.append((start_idx, end_idx, sim))
            edges.append((end_idx, start_idx, sim))

edges

{'바나나', '수박', '파인애플', '딸기', '사과'}
{'바나나', '딸기', '포도', '사과'}
{'바나나', '딸기', '사과'}
{'바나나', '수박', '파인애플', '포도', '딸기', '사과'}
{'바나나', '수박', '파인애플', '딸기', '사과'}
{'수박', '복숭아'}
{'수박'}
{'바나나', '딸기', '사과', '복숭아', '수박', '파인애플'}
{'바나나', '수박', '파인애플', '딸기', '사과'}
{'바나나', '딸기', '파인애플', '사과'}
{'바나나', '딸기', '파인애플', '사과'}
{'바나나', '수박', '파인애플', '딸기', '사과'}
{'바나나', '딸기', '포도', '사과'}
{'수박', '복숭아'}
set()
{'바나나', '딸기', '사과', '수박', '복숭아', '포도'}
{'바나나', '딸기', '포도', '사과'}
{'바나나', '딸기', '파인애플', '사과'}
{'바나나', '딸기', '사과'}
{'바나나', '파인애플', '포도', '딸기', '사과'}
{'수박', '복숭아'}
{'바나나', '딸기', '파인애플', '사과'}
set()
{'바나나', '딸기', '사과', '수박', '복숭아', '파인애플'}


[(0, 1, 0.5),
 (1, 0, 0.5),
 (0, 2, 0.16666666666666666),
 (2, 0, 0.16666666666666666),
 (0, 3, 0.8),
 (3, 0, 0.8),
 (1, 3, 0.6),
 (3, 1, 0.6)]

In [75]:
node_scores = []

for node_idx in range(len(sentences)):
    weight_sum = 0
    for edge in edges:
        start_sent_idx = edge[0]
        end_sent_idx = edge[1]
        weight = edge[2]
        if end_sent_idx == node_idx:
            weight_sum += weight
    
    node_scores.append(weight_sum)

node_scores

[1.4666666666666668, 1.1, 0.16666666666666666, 1.4]

In [76]:
for node_idx in range(len(sentences)):
    for edge in edges:
        print(edge)

(0, 1, 0.5)
(1, 0, 0.5)
(0, 2, 0.16666666666666666)
(2, 0, 0.16666666666666666)
(0, 3, 0.8)
(3, 0, 0.8)
(1, 3, 0.6)
(3, 1, 0.6)
(0, 1, 0.5)
(1, 0, 0.5)
(0, 2, 0.16666666666666666)
(2, 0, 0.16666666666666666)
(0, 3, 0.8)
(3, 0, 0.8)
(1, 3, 0.6)
(3, 1, 0.6)
(0, 1, 0.5)
(1, 0, 0.5)
(0, 2, 0.16666666666666666)
(2, 0, 0.16666666666666666)
(0, 3, 0.8)
(3, 0, 0.8)
(1, 3, 0.6)
(3, 1, 0.6)
(0, 1, 0.5)
(1, 0, 0.5)
(0, 2, 0.16666666666666666)
(2, 0, 0.16666666666666666)
(0, 3, 0.8)
(3, 0, 0.8)
(1, 3, 0.6)
(3, 1, 0.6)


In [77]:
d = 0.85
def cal_score():
    new_scores = []
    for node_idx in range(len(nodes)):
        # edges 반복문, 끝 노드 == 나, 
        # 시작 노드를 come_nodes에 저장
        come_nodes = []
        for sn, en, score in edges:
            if en == node_idx:
                come_nodes.append(sn)
        
        weight_edge_sum = 0
        # come_nodes를 하나씩 꺼내서
        for start_node in come_nodes:
            # edges에 시작노드가 해당 노드면,
            # 일단 다 가져오기 (엣지 가중치 합 확인)
            en_score = 0
            total_score = 0
            for sn, en, score in edges:
                if sn == start_node:
                    # 끝 노드가 나면, 
                    if en == node_idx:
                        en_score = score
                    # start_edges.append((en, score))
                    total_score += score
            
            # 연결 선 가중치 / 나가는 엣지 가중치 합 * 스코어
            # 0.5 / 1.1 * 1.1 = 0.5
            weight_edge = en_score / total_score * node_scores[start_node]
            # 이것들을 전부 더한 뒤,
            weight_edge_sum += weight_edge

        # 수식 적용
        new_scores.append(1-d + d * weight_edge_sum)
    return new_scores

for epoch in range(30):
    node_scores = cal_score()
node_scores

[1.4106820834674991,
 1.024827592596699,
 0.28626521835289565,
 1.2792425401955443]

In [78]:
# numpy array
edges = np.zeros((len(nodes), len(nodes)))
edges

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

---
### 내가 가지고 있는 것
- sentences
- node_scores
- edges(노드, 노드, weight)

### 노드 점수를 계산
- 1 - d + d * 나에게 들어오는 엣지 가중치 합
- 나에게 들어오는 엣지 가중치 합은 어떻게 구할 것인지?

In [79]:
sentences

['딸기 바나나 사과 파인애플 수박', '바나나 사과 딸기 포도', '복숭아 수박', '파인애플 사과 딸기 바나나']

In [80]:
for start_idx in range(len(sentences) - 1):
    for end_idx in range(start_idx+1, len(sentences)):
        sim = sentence_similarity(nodes[start_idx], nodes[end_idx])
        edges[start_idx, end_idx] = sim
        edges[end_idx, start_idx] = sim

edges

{'바나나', '수박', '파인애플', '딸기', '사과'}
{'바나나', '딸기', '포도', '사과'}
{'바나나', '딸기', '사과'}
{'바나나', '수박', '파인애플', '포도', '딸기', '사과'}
{'바나나', '수박', '파인애플', '딸기', '사과'}
{'수박', '복숭아'}
{'수박'}
{'바나나', '딸기', '사과', '복숭아', '수박', '파인애플'}
{'바나나', '수박', '파인애플', '딸기', '사과'}
{'바나나', '딸기', '파인애플', '사과'}
{'바나나', '딸기', '파인애플', '사과'}
{'바나나', '수박', '파인애플', '딸기', '사과'}
{'바나나', '딸기', '포도', '사과'}
{'수박', '복숭아'}
set()
{'바나나', '딸기', '사과', '수박', '복숭아', '포도'}
{'바나나', '딸기', '포도', '사과'}
{'바나나', '딸기', '파인애플', '사과'}
{'바나나', '딸기', '사과'}
{'바나나', '파인애플', '포도', '딸기', '사과'}
{'수박', '복숭아'}
{'바나나', '딸기', '파인애플', '사과'}
set()
{'바나나', '딸기', '사과', '수박', '복숭아', '파인애플'}


array([[0.        , 0.5       , 0.16666667, 0.8       ],
       [0.5       , 0.        , 0.        , 0.6       ],
       [0.16666667, 0.        , 0.        , 0.        ],
       [0.8       , 0.6       , 0.        , 0.        ]])

In [81]:
node_scores = edges.sum(axis=1)
node_scores

array([1.46666667, 1.1       , 0.16666667, 1.4       ])

In [82]:
edges = edges/edges.sum(axis=0).reshape(-1, 1)
edges

array([[0.        , 0.34090909, 0.11363636, 0.54545455],
       [0.45454545, 0.        , 0.        , 0.54545455],
       [1.        , 0.        , 0.        , 0.        ],
       [0.57142857, 0.42857143, 0.        , 0.        ]])

In [83]:
for epoch in range(1):
    weighted_edge_matrix = edges * node_scores.reshape(-1, 1)
    node_scores = 1 - d + d * weighted_edge_matrix.sum(axis=1)

node_scores

array([1.39666667, 1.085     , 0.29166667, 1.34      ])

In [84]:
weighted_edge_matrix

array([[0.        , 0.5       , 0.16666667, 0.8       ],
       [0.5       , 0.        , 0.        , 0.6       ],
       [0.16666667, 0.        , 0.        , 0.        ],
       [0.8       , 0.6       , 0.        , 0.        ]])

In [85]:
# broadcast
edges+np.array((1.0, 0.0, 1.0, 0.0)).reshape(-1, 1)

array([[1.        , 1.34090909, 1.11363636, 1.54545455],
       [0.45454545, 0.        , 0.        , 0.54545455],
       [2.        , 1.        , 1.        , 1.        ],
       [0.57142857, 0.42857143, 0.        , 0.        ]])

### 3) 문장 중요도 계산

### 4) 문서 요약

In [ ]:
import nltk
nltk.download('punkt')



---



## 2.2 TextRank 구현 (Graph 활용)

In [52]:
Text = "딸기 바나나 사과 딸기 파인애플. 바나나 사과 딸기. 복숭아 파인애플. 파인애플 사과 딸기 바나나."

### 2) 토큰화

In [53]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [55]:
def sentences(text):
    return sent_tokenize(text)

### 3) 자카드 유사도

In [56]:
from konlpy.tag import Mecab

# 문장간 유사도 측정 (자카드 유사도 사용)
def sentence_similarity(sentence1, sentence2):
    mecab = Mecab()
    # 각 문장을 소문자로 변환
    sentence1 = [word for word in mecab.pos(sentence1) if word[1][0] in ['N', 'V']]
    sentence2 = [word for word in mecab.pos(sentence2) if word[1][0] in ['N', 'V']]

    union = set(sentence1).union(set(sentence2))
    intersection = set(sentence1).intersection(set(sentence2))
    return len(intersection)/len(union) 

sentence_similarity('나는 치킨을 좋아해','나는 치킨을 싫어해')

0.5

In [57]:
def connect(nodes):
    return [(start,end ,sentence_similarity(start, end)) 
        for start in nodes for end in nodes if start is not end]

### 3) 그래프 생성

In [58]:
import networkx as nx

def rank(nodes,edges):
    graph=nx.diamond_graph()
    graph.clear() 
    graph.add_nodes_from(nodes)
    graph.add_weighted_edges_from(edges)

    return nx.pagerank(graph)

### 4) 문서 요약

In [59]:
def summarize(text,num_summaries=3):
    nodes=sentences(text)
    edges=connect(nodes)
    scores=rank(nodes,edges)
    return sorted(scores.items(), key=lambda x: x[1], reverse=True)[:num_summaries]

In [60]:
summary=summarize(doc, 3)

for sent in summary :
    print(sent)

('또 다른 우주 산업계 관계자는 국내 기업이 스페이스 데이터 사업에서 올릴 수 있는 성과가 많다고 설명했다.', 0.022032003200628196)
('정부는 과학기술정보통신부(과기정통부)를 중심으로 스페이스 데이터 시장의 기반이 되는 인공위성 분야는 물론 우주 발사체 등을 개발하는 사업을 추진하고 있다.', 0.021406176387686257)
('26일 업계에 따르면 정보통신기술(ICT) 업체부터 방산 기업까지 정부의 우주산업 육성 계획에 맞춰 스페이스 데이터 시장 진출을 준비하고 있다.', 0.02101054429366911)


## 2.3 gensim을 활용한 요약

- summarization.summarizer.summarize() : 문서 요약

In [61]:
doc

'업종을 가리지 않고 다양한 국내 기업들이 우주산업을 ‘미래 먹거리’로 주목하고 있다. 여러 우주산업 분야 중에서도 특히 비교적 진출 문턱이 낮은 ‘스페이스 데이터(Space Data)’에서 기회를 잡겠단 청사진을 그렸다.\n\n26일 업계에 따르면 정보통신기술(ICT) 업체부터 방산 기업까지 정부의 우주산업 육성 계획에 맞춰 스페이스 데이터 시장 진출을 준비하고 있다. ‘우주 데이터 산업의 쌀’로 비유되는 스페이스 데이터는 인공위성에서 촬영한 지구 관측 영상·이미지 등 우주를 통해 오가는 다양한 정보들을 통틀어 부르는 말이다. 인공지능(AI)·빅데이터 등을 활용해 △국토·자원 관리 △재해·재난 대응 △농업 △금융 △부동산 △물류 △환경 등 매우 다양한 산업에서 새로운 사업적 가치가 창출될 것으로 기대받는 분야다.\n\n정부는 과학기술정보통신부(과기정통부)를 중심으로 스페이스 데이터 시장의 기반이 되는 인공위성 분야는 물론 우주 발사체 등을 개발하는 사업을 추진하고 있다. 이를 통해 민간 주도의 우주산업 생태계를 육성하겠단 목표를 세웠다.\n\n전통적인 ICT 기업인 이동통신 3사(SK텔레콤·KT·LG유플러스, 이하 이통3사)는 이 같은 분위기를 반영, 인공위성을 기반으로 한 데이터 시장을 차세대 사업으로 선정했다. 네이버·한글과컴퓨터(한컴) 등 플랫폼 기업도 마찬가지다. 이들 기업은 그간 쌓아온 자사 인프라에 ‘스페이스 데이터’를 추가하는 식으로 사업을 구상 중이다.\n\n최근에는 방산 기업인 LIG넥스원과 한국항공우주산업(KAI) 등도 해당 시장에서 사업적 성과를 올리기 위해 협업의 폭을 확대하고 있다. 스페이스 데이터뿐 아니라 인공위성 제작에도 관심을 나타내며 사업 영역을 넓히기 위한 전략을 추진 중이다.\n\n국내 굴지의 기업들이 스페이스 데이터 시장에 주목하는 이유는 국내 우주산업 생태계의 모습이 반영된 현상으로 보인다. 정부 발표에 따르면 2020년 기준 우리나라 우주산업 규모는 3조2610억원 수준이다. 세계 우주산업 시장 규모는 2019년 기준 

In [62]:
from gensim.summarization.summarizer import summarize
print(summarize(doc))

26일 업계에 따르면 정보통신기술(ICT) 업체부터 방산 기업까지 정부의 우주산업 육성 계획에 맞춰 스페이스 데이터 시장 진출을 준비하고 있다.
정부는 과학기술정보통신부(과기정통부)를 중심으로 스페이스 데이터 시장의 기반이 되는 인공위성 분야는 물론 우주 발사체 등을 개발하는 사업을 추진하고 있다.
스페이스 데이터뿐 아니라 인공위성 제작에도 관심을 나타내며 사업 영역을 넓히기 위한 전략을 추진 중이다.
국내 굴지의 기업들이 스페이스 데이터 시장에 주목하는 이유는 국내 우주산업 생태계의 모습이 반영된 현상으로 보인다.
우주 산업계 관계자는 “국내 다양한 기업들이 스페이스 데이터 사업에서 새로운 기회를 발굴하고자 하는 이유는 해당 분야의 성장 가능성을 반영한 것”이라면서도 “국내 우주산업 생태계를 고려하면 사업적 성과를 올릴 수 있다고 판단되는 분야가 사실상 스페이스 데이터 뿐이기도 하다”고 말했다.
또 다른 우주 산업계 관계자는 국내 기업이 스페이스 데이터 사업에서 올릴 수 있는 성과가 많다고 설명했다.
그는 “인공위성을 통해 확보한 데이터를 사용하는 곳은 결국 지상”이라며 “IT강국을 이끄는 국내 기업들이 보유한 인공지능(AI)·통신·보안 등의 기술을 통해 데이터를 재가공하면 세계 시장에서 충분히 성과를 낼 수 있을 것”이라고 말했다.
누리호의 성공 역시 스페이스 데이터 분야의 성장을 촉진할 요소다.
정부는 누리호의 기술을 민간에 이전해 우주산업 생태계를 키우겠단 계획을 진행하고 있다.
민간이 우주 운송 수단을 확보하게 된다면 자연스럽게 국내 스페이스 데이터 시장의 규모도 커질 수 있는 구조다.
이에 따라 스페이스 데이터 시장의 성장도 가파를 것으로 분석된다.
KT 샛은 이 기간 쌓은 ‘국제 협력’을 바탕으로 스페이스 데이터 사업 진출을 준비 중이다.
KT 샛은 우선 국내 시장을 대상으로 레퍼런스를 확보, 스페이스 데이터 사업의 서비스 포트폴리오를 다각화를 추진한다.
한컴그룹에선 2020년 합류한 우주·드론 전문기업 한컴인스페이스가 스페이스 데이터 사업을 담당

c:\Users\user\anaconda3\envs\mecab\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [63]:
Text = "딸기 바나나 사과 파인애플. 바나나 사과 딸기 포도. 복숭아 포도. 파인애플 사과 딸기 바나나."

In [65]:
from gensim.summarization.summarizer import summarize
print(summarize(Text))