### Numpy practice for nlp

In [1]:
import numpy as np

- 1차원 배열

In [6]:
vec = np.array([1,2,3,4,5])
vec

array([1, 2, 3, 4, 5])

In [8]:
print(type(vec))

<class 'numpy.ndarray'>


In [10]:
vec.ndim, vec.shape

(1, (5,))

- 2차원 배열

In [11]:
mat = np.array([[10,20,30], [60,70,80]])
mat

array([[10, 20, 30],
       [60, 70, 80]])

In [12]:
print(type(mat))

<class 'numpy.ndarray'>


In [13]:
mat.ndim, mat.shape

(2, (2, 3))

- ndarray 초기화

In [15]:
zero_mat = np.zeros((2,3))
print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
one_mat = np.ones((2,3))
print(one_mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
same_value_mat = np.full((2,2), 7)
print(same_value_mat)

[[7 7]
 [7 7]]


In [18]:
eye_mat = np.eye(3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
random_mat = np.random.random((2,2))
print(random_mat)

[[0.40846683 0.38331884]
 [0.51270338 0.57600576]]


- np.arange()

In [20]:
range_vec = np.arange(10)
print(range_vec)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
n = 2
range_n_step_vec = np.arange(1, 10, n)
print(range_n_step_vec)

[1 3 5 7 9]


- np.reshape()

In [30]:
reshape_mat = np.arange(30).reshape((5,6))
print(reshape_mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


- numpy 슬라이싱

In [31]:
mat = np.array([[1,2,3], [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [32]:
# 첫 번째 행 출력
slicing_mat = mat[0, :]
print(slicing_mat)

[1 2 3]


In [36]:
# 두 번째 열 출력
slicing_mat = mat[:, 1]
print(slicing_mat)

[2 5]


- numpy 정수 인덱싱

In [37]:
mat = np.array([[1,2], [4,5], [7,8]])
print(mat)

[[1 2]
 [4 5]
 [7 8]]


In [39]:
# 원소 1개 가져오기 -> 1행 0열
mat[1,0]

4

In [40]:
# 원소 2개 가져오기 -> 2행, 1행, 0열, 1열
indexing_mat = mat[[2,1], [0,1]]
print(indexing_mat)

[7 5]


- numpy 연산

In [41]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [46]:
print(np.add(x,y), x + y)

[5 7 9] [5 7 9]


In [47]:
print(np.subtract(x,y), x -y)

[-3 -3 -3] [-3 -3 -3]


In [50]:
print(np.multiply(np.subtract(x,y), x))
print(np.subtract(x,y) * x)

[-3 -6 -9]
[-3 -6 -9]


In [53]:
print(np.divide(np.subtract(x,y), x))
print(np.subtract(x,y) / x)

[-3.  -1.5 -1. ]
[-3.  -1.5 -1. ]


- dot()

In [57]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
print(mat1)
print(mat2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [58]:
mat3 = np.dot(mat1, mat2)
print(mat3)

[[19 22]
 [43 50]]
