https://www.geeksforgeeks.org/one-hot-encoding-in-nlp/

In [11]:
import numpy as np

# Define the corpus of text
corpus = [
	"The quick brown fox jumped over the lazy dog.",
	"She sells seashells by the seashore.",
	"Peter Piper picked a peck of pickled peppers."
]

# Create a set of unique words in the corpus
unique_words = set()
for sentence in corpus:
	for word in sentence.split():
		unique_words.add(word.lower())

# Create a dictionary to map each
# unique word to an index
word_to_index = {}
for i, word in enumerate(unique_words):
	word_to_index[word] = i

# Create one-hot encoded vectors for
# each word in the corpus
one_hot_vectors = []
for sentence in corpus:
	sentence_vectors = []
	for word in sentence.split():
		vector = np.zeros(len(unique_words))
		vector[word_to_index[word.lower()]] = 1
		sentence_vectors.append(vector)
	one_hot_vectors.append(sentence_vectors)

# Print the one-hot encoded vectors
# for the first sentence
print("One-hot encoded vectors for the first sentence:")
for vector in one_hot_vectors[0]:
	print(vector)


One-hot encoded vectors for the first sentence:
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
import numpy as np

# Define the sentences
sentences = [
	'The cat sat on the mat.',
	'The dog chased the cat.',
	'The mat was soft and fluffy.'
]

# Create a vocabulary set
vocab = set()
for sentence in sentences:
	words = sentence.lower().split()
	for word in words:
		vocab.add(word)

# Create a dictionary to map words to integers
word_to_int = {word: i for i, word in enumerate(vocab)}

# Create a binary vector for each word in each sentence
vectors = []
for sentence in sentences:
	words = sentence.lower().split()
	sentence_vectors = []
	for word in words:
		binary_vector = np.zeros(len(vocab))
		binary_vector[word_to_int[word]] = 1
		sentence_vectors.append(binary_vector)
	vectors.append(sentence_vectors)

# Print the one-hot encoded vectors for each word in each sentence
for i in range(len(sentences)):
	print(f"Sentences {i + 1}:")
	for j in range(len(vectors[i])):
		print(f"{sentences[i].split()[j]}: {vectors[i][j]}")


Sentences 1:
The: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
cat: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sat: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
on: [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
the: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
mat.: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
Sentences 2:
The: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
dog: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
chased: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
the: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
cat.: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Sentences 3:
The: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
mat: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
was: [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
soft: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
and: [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
fluffy.: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


---

In [13]:
# Define the sentences
sentences = [
	'The cat sat on the mat.',
	'The dog chased the cat.',
	'The mat was soft and fluffy.'
]

# Create a vocabulary set
vocab = set()
for sentence in sentences:
	words = sentence.lower().split()
	print(words)
	for word in words:
		print(word)
		vocab.add(word)

['the', 'cat', 'sat', 'on', 'the', 'mat.']
the
cat
sat
on
the
mat.
['the', 'dog', 'chased', 'the', 'cat.']
the
dog
chased
the
cat.
['the', 'mat', 'was', 'soft', 'and', 'fluffy.']
the
mat
was
soft
and
fluffy.


In [14]:
vocab

{'and',
 'cat',
 'cat.',
 'chased',
 'dog',
 'fluffy.',
 'mat',
 'mat.',
 'on',
 'sat',
 'soft',
 'the',
 'was'}

In [15]:
word_to_int = {word: i for i, word in enumerate(vocab)}
word_to_int

{'cat': 0,
 'on': 1,
 'fluffy.': 2,
 'cat.': 3,
 'mat': 4,
 'the': 5,
 'chased': 6,
 'was': 7,
 'sat': 8,
 'and': 9,
 'soft': 10,
 'dog': 11,
 'mat.': 12}

In [16]:
# Create a binary vector for each word in each sentence
vectors = []
for sentence in sentences:
	words = sentence.lower().split()
	print(words)
	sentence_vectors = []
	for word in words:
		binary_vector = np.zeros(len(vocab))
		binary_vector[word_to_int[word]] = 1
		print(binary_vector)
		sentence_vectors.append(binary_vector)
	vectors.append(sentence_vectors)


['the', 'cat', 'sat', 'on', 'the', 'mat.']
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
['the', 'dog', 'chased', 'the', 'cat.']
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
['the', 'mat', 'was', 'soft', 'and', 'fluffy.']
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
vectors

[[array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])],
 [array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]),
  array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])],
 [array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 

In [18]:
# Print the one-hot encoded vectors for each word in each sentence
for i in range(len(sentences)):
	print(f"Sentences {i + 1}:")
	for j in range(len(vectors[i])):
		print(f"{sentences[i].split()[j]}: {vectors[i][j]}")

Sentences 1:
The: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
cat: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sat: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
on: [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
the: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
mat.: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
Sentences 2:
The: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
dog: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
chased: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
the: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
cat.: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Sentences 3:
The: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
mat: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
was: [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
soft: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
and: [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
fluffy.: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
for i in range(len(sentences)): # 0~2
	print(i + 1)
	for j in range(len(vectors[i])): # 0~5
		print(sentences[i].split()[j])
		print(vectors[i][j])

1
The
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
cat
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sat
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
on
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
the
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
mat.
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
2
The
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
dog
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
chased
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
the
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
cat.
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
3
The
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
mat
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
was
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
soft
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
and
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
fluffy.
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
