In [1]:
import numpy as np
x_data = np.linspace(2, 20, 10).reshape(10, 1)
t_data = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1]).reshape(10, 1)
# x_data - 공부시간
# t_data - 합격여부 0 불합격, 1 합격
print(x_data)
print(t_data)

[[ 2.]
 [ 4.]
 [ 6.]
 [ 8.]
 [10.]
 [12.]
 [14.]
 [16.]
 [18.]
 [20.]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]


In [2]:
np.linspace(2, 20, 10).reshape(10, -1)

array([[ 2.],
       [ 4.],
       [ 6.],
       [ 8.],
       [10.],
       [12.],
       [14.],
       [16.],
       [18.],
       [20.]])

In [3]:
# H(x) = Wx + b
W = np.random.rand(1, 1)
b = np.random.rand(1)
print(f"Wx + b : {W}x + {b}")

Wx + b : [[0.60729996]]x + [0.46964722]


In [4]:
np.random.rand(1)

array([0.9892067])

In [5]:
np.random.rand(1,1)

array([[0.70846405]])

In [6]:
# 활성화 함수 Activation Func
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [7]:
def loss_func(x, t):

    delta = 1e-7

    z = np.dot(x, W) + b # Wx + b
    y = sigmoid(z)
    
    # Cross-Entropy Func
    # delta 무한대, 마이너스 무한대 방지
    return -np.sum( t*np.log( y + delta ) + (1-t)*np.log((1-y) + delta) )

In [8]:
learning_rate = 1e-2
f = lambda x : loss_func(x_data, t_data)

In [9]:
def derivative(f, var):
    delta = 1e-5
    grad = np.zeros_like(var)
    it = np.nditer(var, flags=["multi_index"], op_flags=["readwrite"])
    # print(x)
    # print(var)
    while not it.finished:
        idx = it.multi_index
        tmp_val = var[idx]
        var[idx] = float(tmp_val) + delta
        fx1 = f(var[idx])
        var[idx] = float(tmp_val) - delta
        fx2 = f(var[idx])
        grad = ((fx1 - fx2) / (2*delta))
        var[idx] = tmp_val
        it.iternext()
    return grad

In [10]:
for step in range(100001):
    W -= learning_rate * derivative(f, W)
    b -= learning_rate * derivative(f, b)
    if ( step % 5000  == 0 ):
        print(f"step : {step}, loss_value : {loss_func(x_data, t_data)}")

step : 0, loss_value : 11.879681501633687


step : 5000, loss_value : 0.845286561116133
step : 10000, loss_value : 0.6210111480014967
step : 15000, loss_value : 0.5095086117684672
step : 20000, loss_value : 0.43779437704404583
step : 25000, loss_value : 0.3861582188225886
step : 30000, loss_value : 0.3465348874184678
step : 35000, loss_value : 0.31485792206496555
step : 40000, loss_value : 0.28879648097881727
step : 45000, loss_value : 0.26689307463348827
step : 50000, loss_value : 0.24817722318656057
step : 55000, loss_value : 0.231971367261949
step : 60000, loss_value : 0.2177846539334924
step : 65000, loss_value : 0.20525081649345878
step : 70000, loss_value : 0.19408986008714155
step : 75000, loss_value : 0.18408338196668592
step : 80000, loss_value : 0.17505809032698172
step : 85000, loss_value : 0.1668744581698237
step : 90000, loss_value : 0.15941870672205138
step : 95000, loss_value : 0.15259701293057729
step : 100000, loss_value : 0.1463312414244847


In [12]:
print(W, b)

[[2.58754428]] [-33.55471428]


In [13]:
def predict(test_data):
    z = np.dot(test_data, W) + b
    y = sigmoid(z)
    result = 0
    if y >= 0.5:
        result = 1 # Pass
    else:
        retule = 0 # Fail
    return y, result

In [34]:
y, result = predict(np.array([12.968]))
print(y, result)

[0.50014] 1
